#import "./note_for_myself.typ": *

#show: article_settings.with(
  section_level: "section",
  heading_number_mode: "level3-last",
  title: "title",
  author: "The author",
  date: datetime.today().display(),
  author_page: link("https://www.example.com")[My Homepage],
  version: "1.0.0",
)

#let CH = math.op("CH")
#let kk = math.bold("k")
#let Div = math.op("Div")
#let Pic = math.op("Pic")
#let Cl = math.op("Cl")
#let ord = math.op("ord")
#let fkk = math.scr("K")
#let rank = math.op("rank")
#let supp = math.op("supp")
#let divisor = math.op("div")
#let Spec = math.op("Spec")
#let calO = math.cal("O")
#let calF = math.cal("F")
#let calN = math.cal("N")
#let calT = math.cal("T")
#let calE = math.cal("E")
#let Yang(content) = text(red)[Yang: #content]

== March 10: divisors

A goal for us in the coming weeks is to define intersection products for Chow groups.

#example[
  Let $X$ be a topological space. 
  The cap product is defined on singular homology and cohomology on $X$ as follows:
  $ H_i (X,ZZ) times.o H^j (X,ZZ) -> H_{i-j}(X,ZZ), #h(1em), (sigma, psi) |-> psi(sigma|) $
  $H^j (X,ZZ)$ may be regarded as the collection of operations on $H_circle.filled.small (X, ZZ)$ with grading shift $-j$.
]

For a scheme $X$, we will define 
$ CH_i (X) times.o \" CH^i (X) \" -> CH_(i-j) (X), $
where "$CH^i (X)$" contains the $j$-th Chern class of vector bundles on $X$.
The simplest case is $j = 1$, corresponding to line bundles or Cartier divisors.

=== Divisors

#definition[
  Let $X$ be a $n$-dimensional variety.
  A _Weil divisor_ on $X$ will mean an $(n-1)$-cycle on $X$.
  A _Cartier divisor_ on $X$ is defined by data ${(U_alpha, f_alpha)}$ where ${U_alpha}$ is an open cover of $X$ and $f_alpha$ is a non-zero rational function on $U_alpha$ such that $f_alpha \/ f_beta$ is a unit on $U_alpha inter U_beta$.
  In other words, it is an element of 
  $ Div (X) := Gamma (X, fkk(X)^times \/ calO_X^times). $
  A Cartier divisor is called _principal_ if it lies in the image of the natural map 
  $ Gamma (X, fkk(X)^times) -> Div (X) $.
  Two Cartier divisors are called _linearly equivalent_ if their difference is principal, and we write $D tilde D'$.
]

Note 
- $ 0 -> calO_X^times -> fkk(X)^times -> Div (X) -> 0 $ is exact, hence we have the induced map
  $ Div (X) -> Pic (X) tilde.equiv H^1 (X, calO_X^times)  $.

- we have the natural map $Div (X) -> Z_{n-1} (X)$ sending a Cartier divisor ${(U_alpha, f_alpha)}$ to a Weil divisor $sum_V ord_V (f_alpha) dot V$, where $V$ runs through all irreducible subvarieties of codimension 1 in $X$ and $ord_V (f_alpha)$ is the order of vanishing of $f_alpha$ along $V$ whenever $V inter U_alpha eq.not emptyset$.

#example[
  If $X$ is a smooth variety, $Pic (X) tilde.equiv CH_(n-1) (X)$.
  In general, the map $Pic (X) -> CH_(n-1) (X)$ is neither injective nor surjective.
  For instance, $X := {x y = z^2} subset AA^3$ and $l := {x = z = 0} subset X$ is a Weil divisor that is not Cartier.
  And $CH_1 (X) = Cl (X) = ZZ\/2$ generated by $[l]$.
  This implies $Pic(X) -> CH_1 (X)$ is the zero map.
  In fact, this is injective (using $X$ is normal), so $Pic(X) = 0$.
]

Note that the definition of Cartier divisors extends to schemes.
(But $Div(X) \/ tilde --> Pic (X)$ is NOT an isomorphism in general!)

=== Intersection with divisors

Line bundles always can be pull-backed, so do Cartier divisors modulo linear equivalence.

#example[
  Let $pi: tilde(AA^n) -> AA^n$ be the blow-up of $AA^n$ at the origin, and let $PP^(n-1) tilde.equiv E subset tilde(AA^n)$ be the exceptional divisor.
  Then $calO_(AA^n)(E)|_E = calN_(E\/tilde(AA^n)) = calO_E(-1)$, but $E$ does NOT pull-back to $E$.
]

For a Cartier divisor $D$ on a scheme $X$, define the _support_ of $D$ to be
$ |D| := supp (D) := union.big_(V subset X, ord_V(D) eq.not 0) V $.

#definition[
  A _pseudo-divisor_ on $X$ is a triple $(L,Z,s)$ where 
  - $L$ is a line bundle on $X$, 
  - $Z subset X$ is a closed subset of $X$, 
  - $s$ is a nowhere vanishing section on $L|_(X-Z)$,
  which is either
  - $(L,X,1)$ for some line bundle $L$ on $X$, or
  - $(calO_X (D), |D|, s_D)$ for some Cartier divisor $D$ on $X$, where $s_D$ corresponds to $1 in fkk(X)^times$ with $calO_X (D) subset fkk(X)^times$.
]

We also denote a pseudo-divisor $D$ and the corresponding triple by $(L_D, |D|, s_D)$.

For pseudo-divisors $D$ and $D'$, 
#align[
  $D + D' := (L_D times.o L_D', |D| union |D'|, s_D times.o s_D')$
  $- D := (L_D^(-1), |D|, s_D^(-1))$
]
For a morphism $f:Y -> X$, $f^* D := (f^* L_D, f^(-1) (|D|), f^* s_D)$.

When $X$ is an $n$-dimensional variety, define $[D] in CH_(n-1) (|D|)$ to be 
#Yang[]

#definition[]

For an $i$-cycle $alpha = sum n_V [V]$ on $X$, define $D dot alpha = sum n_V D dot [V] in CH_(i-1)(|D| inter |alpha|)$, where $|alpha| := union.big_(n_V eq.not 0 V)$ is the support of $alpha$.

#example[
  Let $X$ be a purely $n$-dimensional scheme, $D$ be a Cartier divisor on $X$.
  Then $D dot [X] = [D]$ by Lemma on Week 1, Thursday.
]

#proposition[
  Let $X$ be a scheme, $D,D'$ be pseudo-divisors on $X$, $alpha,alpha'$ be $i$-cycles on $X$.
  Then $D dot (alpha + alpha') = D dot alpha + D dot alpha' in CH_(i-1)(|D| inter (|alpha| union |alpha'|))$

  $(D+D') dot alpha = D dot alpha + D' dot alpha in CH_(i-1)((|D| union |D'|) inter |alpha|)$

  Let $f: X -> Y$ be a proper morphsim, $alpha$ be an $i$-cycle on $X$, $D$ be a pseudo-divisor on $Y$, 
  then $f_* (f^* D dot alpha) = D dot alpha in CH_(i-1)(|D| inter f(|alpha|))$.

  Let $f:X -> Y$ be a flat morphism of relative dimension $n$, $alpha$ be an $i$-cycle on $Y$, $D$ be a pseudo-divisor on $Y$, then 
  $ f^* (D dot alpha) = f^* D dot f^* alpha in CH_(i+n-1)(f^(-1) (|D|) inter f^(-1)(|alpha)). $

  Let $D$ be a pseudo-divisor on a scheme $X$ s.t. $L_D tilde.equiv calO_X$.
  Then, for all $i$-cycles $alpha$ on $X$, $D dot alpha = in CH_(i-1) (|alpha|).$
]
#proof[
  (a) By definition

  Hence in (b)-(e), may assume $alpha = [v]$ for some variety $V$.

  (b) By linearity of restricting pseudo-divisors to a subvariety and taking the class of pseudo-divisors.

  (c) If $f$ is a closed embedding, it is ok.
  In general, may assume: $X$ is a variety, $alpha = [X]$, $f:X -> Y$ is surjective proper, $D$ is a Cartier divisor.
  WTS, $f^* f_* [D] = deg (X\/Y) [D]$.
  By working locally, may assume $D = divisor(r)$ for some $f in fkk (X)^times$, then 
  $ f_* f^* divisor(r) = divisor(r^d) = d divisor(r),$
  where $d = deg (X/Y)$.

  (d) May assume: $Y$ is a variety and $alpha = [Y]$, 
  WTS: $f^* [D] = [f^-1(D)]$ by lemma in Week 1 Thursday.

  (e) May assume $X$ is a variety, $alpha = [X]$, $D = divisor(r)$ for some $r in fkk(X)^times$, then $divisor(r) dot [X] = divisor(r) = 0 in CH_(i-1)(X)$.
]

#theorem[
  Let $D,D'$ be Cartier divisors on an $n$-dimensional variety $X$.
  Then 
  $ D dot [D'] = D' dot [D] in CH_(n-2)(|D| inter |D'|). $
]
#proof[
  #case[
    $D,D'$ are effective Cartier divisors (i.e. codimension $1$ closed subschemes, locally defined by single non zero divisors).
  ]    
  By induction on:
    $ calE(D,D') := max {ord_V (D) ord_V (D') | V subset X "of codimension " 1 }. $

  The basis case is $calE(D,D') = 0$, i.e. $D$ and $D'$ intersect properly.
  Let $W subset X$ a codimension $2$ subvariety, $A := calO_{X,W}$, $a, a' in A$ be local equations of $D$ and $D'$.
  Let $V subset X$ be a codimension $1$ subvariety containing $W$ which correspond to a height $1$ prime ideal $p subset A$.
  Then the 
  - coefficient of $[V]$ in $[D']$ is $l(O_{D',V}) = l_A_p (A_p \/ a' A_p)$
  - coefficient of $[W]$ in $D dot [V]$ is $l(O_{D',V}) = l_(A\/p) (A \/ (a A + p A))$.
  Hence the coefficient of $[W]$ in $D dot [D']$ is 
  $ sum_p l_(A_p)(A_o\/a'A_p) l_(A\/p)(A\/(p + a A))$.
  By Fulton A 2.7 and A 2.8, change $a$ and $a'$ is ok.
  By symmetry, $D dot [D'] = [D'] dot [D]$ as cycles.

  Now we assume $calE(D,D') > 0$ (just an idea).
  Let $pi: tilde(X) -> X$ be the blow-up along $D inter D'$, $E subset tilde(X)$ be the exceptional divisor.
  Then $pi^* D = tilde(D) + E, pi^* D' = tilde(D) + E$, where $tilde(D)$ and $tilde(D')$ are effective Cartier divisors such that $tilde(D) inter tilde(D') = emptyset$.
  Moreover, $calE(tilde(D), E), calE(tilde(D'), E) < calE(D, D')$ (for the pf, read Fulton)
  Then 
  $ D dot [D'] = pi_*((tilde(D) + E) dot ([tilde(D')] + [E])) = pi_*((tilde(D') + E) dot ([tilde(D)] + [E])) = D' dot [D]. $ 

  #case[
    $D$ is arbitrary, $D'$ is effective.
  ]

  If $D$ is the difference of $2$ effective Cartier divisors, the proof is reduced to case 1.
  However, this is in general false.

  In general, may assume: $X = Spec A$, $a in fkk(X)^*$ be the local equation for $D$.
  Define $I := {b in A | a dot b in A}$ be the ideal of denominations of $a$.
  Let $pi: tilde(X) -> X$ be the blow-up along $V(I)$, $E$ be the exceptional divisor.
  Then $pi^* D = C - E$, where $C$ is an effective Cartier divisor.
  Since Tho=m holds for $(C , pi^* D'), (E, pi^* D')$, thm holds for $(D,D')$.

  #case[
    $D,D'$ are arbitrary.
    Let $pi:tilde(X) -> X$ as Case 2.
    Since Thm holds for $(C, pi^*D')$ and $(E,pi^*D')$.
    It holds for $(D,D')$.
  ]
]

#corollary[
  Let $X$ be a scheme, $alpha$ be an $i$-cycle on $X$.
  If $alpha tilde 0$ on $X$, then for all pseudo-divisor $D$ on X, $D dot alpha = 0 in CH_(i-1)(|D| inter |alpha|)$.
  In particular, we have well defined 
  $ CH_i (X) -> CH_(i-1) (|D|), alpha |-> D dot alpha. $
]
#proof[
  May assume: $X$ is a variety, $alpha = divisor(f)$ for some $f in fkk(X)^times$.
  Then 
  $ D dot divisor(f) = divisor(f) dot [D] = 0 in CH_(n-2)(|D| inter |alpha|). $
]

#definition[
  Let $X$ be a scheme, $L$ be a line bundle on $X$.
  For an $i$-dimensional subvariety $V$ of $X$, define 
  $ c_1(L) inter [V] := "the class of " L|_V in CH_(i-1)(V). $
]
By Cor, we have well-defined:
$ c_1(L) inter : CH_i(X) -> CH_(i-1) (X). $