#import "../../../Accessories/note_for_myself.typ": *
#import "../../../Accessories/my_macros.typ": *

// // #show: article_settings.with(
// //   section_level: "section",
// //   heading_number_mode: "level3-last",
// //   title: "title",
// //   author: "The author",
// //   date: datetime.today().display(),
// //   author_page: link("https://www.example.com")[My Homepage],
// //   version: "1.0.0",

// //   make_title: false
// // )

#let Yang(content) = text(red)[Yang: #content]
#let bf(content) = math.upright(math.bold([#content]))
#let cong = math.tilde.equiv
#let cup = math.union
#let cap = math.inter
#let indent = [\ #h(2em)]

== Homework 1

In the following, we work over a field $kk$.

#exercise[
  Let $V subset AA^n$ be a closed subvariety of dimension $< n$ with $0 in.not V$ and let $W subset PP^1 times AA^n$ be the closure of the image of the multiplication map 
  $ (AA^1 \\ {0}) times V arrow (AA^1 \\ {0}) times AA^n, quad (t, v) arrow.bar (t, t v). $
  For the first projection $W arrow PP^1$, show that:
  - the fiber over $t=1$ is $V$;
  - the fiber over $t=0$ is the affine cone of $overline(V) inter H$ where $overline(V) subset PP^n$ is the projective closure of $V$ and $H subset PP^n$ is the hyperplane at infinity;
  - the fiber over $t=infinity$ is empty.
  Under the assumption of $\# kk = oo$, deduce that $CH_i (AA^n) = 0$ for all $i < n$.
]
#proof[
  Denote the image of the multiplication map by $U$. 
  Note that $U$ is closed in $GG_m times AA^n$ since it can be defined by ${ f(x\/t) : f in I(V) }$.
  Hence the fiber of $W$ over $t=1$ is equal to the fiber of $U$ over $t=1$, which is $V$. 

  On the affine chart $AA^1 times AA^n$ we consider the closure of $U$.
  For every polynomial $f in kk[X_1, dots, X_n]$, denote by $deg f$ the total degree of $f$.
  Consider the homogenization $f^h in kk[T, X_1, dots, X_n]$ of $f$ with respect to the variable $T$ (i.e., $f^h (T, X_1, dots, X_n) = T^(deg f) f(X_1/T, dots, X_n/T)$).
  Then the closure of $U$ in $AA^1 times AA^n$ is defined by the ideal generated by ${ f^h (T, X_1, dots, X_n) : f in I(V) }$.
  Restricting to the fiber over $t=0$, we get the affine cone of $overline(V) inter H$.

  For the fiber over $t = oo$, we can work on the affine chart $AA^1 times AA^n$ with coordinates $(s, x_1, dots, x_n)$ where $s = 1/t$.
  On this chart, the polynomials $f(x/t) = f(s x)$ is well-defined.
  Note that $0 in.not V$, then there exists $f in I(V)$ with nonzero constant term.
  Then the function $f(s x)$ vanishing on $U$ but is nonzero on the whole fiber over $s=0$.
  Hence the fiber of $W$ over $t = infinity$ is empty.

  Assume the $\# kk = infinity$.
  Then there exists a $kk$-point $x in AA^n \\ V$.
  Let $phi:AA^n arrow AA^n$ be an automorphism sending $0$ to $x$.
  Then $phi^(-1)(V)$ is a closed subvariety of $AA^n$ of dimension $< n$ with $0 in.not phi^(-1)(V)$.
  By the above, we have $[phi^(-1)(V)] = [p^(-1)(0)]-[p^(-1)(infinity)] tilde 0$ in $CH_i (AA^n)$ where $p:W arrow PP^1$ is the first projection.
  Thus $[V] = phi^(-1,*) [phi^(-1)(V)] tilde 0$ in $CH_i (AA^n)$.
  Since $V$ is arbitrary, we get $CH_i (AA^n) = 0$ for all $i < n$.
]

#remark("by author of note")[
  To show $CH_i (AA^n) = 0$, considering the addition map rather than the multiplication map may be more straightforward.
]

#exercise[
  Let $X subset PP^2$ be a smooth conic curve. 
  Show that $deg: CH_0(X) arrow ZZ$ is injective, with image $ZZ$ if $X$ has a $kk$-point and $2ZZ$ otherwise. 
  (Hint: Use the Riemann-Roch theorem for curves. For the image, as an intermediate step, show that if $X$ has a $kk$-point, then $X tilde.equiv PP^1$.)
]
#proof[
  We have $p_a (C) = ((d-1)(d-2)) / 2$ for a smooth plane curve $C$ of degree $d$.
  Hence $p_a (X) = 0$.
  Let $alpha in CH_0(X)$ of degree $0$.
  By Riemann-Roch, we have $h^0(alpha) - h^0(K_X - alpha) = 1$.
  In particular, $h^0 (alpha) gt.eq.slant 1$.
  Similarly, we have $h^0 (-alpha) gt.eq.slant 1$.
  Hence $cal(O)_X (alpha) tilde.equiv cal(O)_X$ and $alpha tilde 0$ in $CH_0(X)$.

  If $X$ has a $kk$-point, saying $P$, then $deg [P] = 1$ and hence $deg: CH_0(X) arrow ZZ$ is surjective.
  
  If $deg$ has image $ZZ$, then there exists $alpha in CH_0(X)$ with $deg alpha = 1$.
  By Riemann-Roch, we have $h^0 (alpha) gt.eq.slant 1$.
  Hence there exists a $kk$-point $P$ on $X$.
  In particular, if $X$ has no $kk$-point, then the image of $deg$ is not $ZZ$.
  Consider the interinterion of $X$ with a line $L$ in $PP^2$.
  The interinterion $X inter L$ consists of at most two points counting multiplicity.
  If $X inter L$ consists of two distinct points or one point with multiplicity $2$, then $X$ has $kk$-points, a contradiction.
  Hence $X inter L$ consists of a single point $P$ whose residue field is a quadratic extension of $kk$.
  Then $deg P = 2$ and hence the image of $deg$ is $2 ZZ$.
]

#exercise[
  Work out Fulton, Example 2.4.5. Namely, with the notation of the example, show $[D] = 2[l]$ and $D dot [l'] = [P]$ and deduce that $[l]$ is not linear equivalent to any Cartier divisor on $X$.
]
#example[Fulton, Example 2.4.5][
   Let $(x:y:z:t)$ be homogeneous on $PP^3$, and let $X$ be the singular cone defined by the equation $z^2 = x y$. 
   Let $D$ be the Cartier divisor on $X$ defined by the equation $x = 0$. 
   Let $l$ be the line $x = z = 0$, $l'$ the line $y = z = 0$, $P$ the point $(0:0:0:1)$. 
   Then $[D] = 2[l]$ and $D dot [l'] = [P]$. 
   It follows from Theorem 2.4 that there cannot be a Cartier divisor $D'$ on $X$ with $[D'] = [l']$, either as cycles or as classes in $A_1(X)$.
]
#proof[
  Easily see that $Supp D = Supp l$ is irreducible.
  Hence we can work on an affine chart ${t eq.not 0}$ with coordinates $x, y, z$.
  On this chart, $l$ is defined by the ideal $(x,z,x y - z^2) = (x,z)$.
  Hence $l$ is a subvariety.
  We have 
  $ cal(O)_(X,l) = (kk[x, y, z] \/ (z^2 - x y))_((x,z)) = upright(bold(K))[frac(z^2, y), z]_((z)) = upright(bold(K))[z]_((z)), $
  where $bf(K) = kk (y)$.
  Hence $Mult_l (D) = ord_(bf(K)[z]_((z))) (z^2/y) = 2$.
  It follows that $[D] = 2[l]$.

  For the intersection $D dot [l']$, by definition, we see that $D dot [l']$ is the cycle on $l'$ defined by the equation $x = 0$.
  Note that $l' = V(y,z) cong bb(P)^1$ with homogeneous coordinate $[x:t]$.
  Hence $D dot [l']$ is the cycle on $bb(P)^1$ defined by the equation $x = 0$, which is just the class $[P]$.

  If there exists a Cartier divisor $D'$ on $X$ with $[D'] = [l]$, then we have $D' dot [l'] = 1/2 D dot [l'] = 1/2 [P]$, which has degree $1/2$, a contradiction.
  // #Yang[to be filled in later]
]

#exercise[
  Work out Fulton, Example 2.5.2. Namely, show (b), (c), (d).
  (Hint: Use the additivity of Hilbert polynomials. For (b), use @Har77[I.7.4]. For (d), use @Fulton13Intersection[A.2.7].)
]
#example([@Fulton13Intersection[Example 2.5.2]])[ Let $X$ be a closed subscheme of $PP^n$ of dimension $<= k$, and let $Gamma (X)$ be the homogeneous coordinate ring of $X$.

#set enum(numbering: "(a)")

+ For $t$ sufficiently large, the dimension of the $t^("th")$ graded piece $Gamma (X)_t$ is a polynomial in $t$ of degree $<= k$ called the Hilbert polynomial (cf. @Har77[I.7.5]). Define $d_k (X)$ to be the coefficient of $t^k / k!$ in this polynomial.

+ If $X_1, ..., X_r$ are the irreducible components of $X$, $m_i$ the multiplicity of $X_i$ in $X$, then $d_k (X) = sum m_i d_k (X_i)$.

+ If $X$ is an irreducible variety, and $H$ is a hypersurface of degree $m$ not containing $X$, then $d_(k-1) (X inter H) = m d_k (X)$. (Here $X inter H$ is the scheme-theoretic intersection, so there are exact sequences 
  $ 0 -> Gamma(X)_(t-m) -> Gamma(X)_t -> Gamma(X inter H)_t -> 0 quad "for" t >> 0.) $

+ For any purely $k$-dimensional subscheme $X$ of $PP^n$,
  $ d_k (X) = deg[X] = integral_(PP^n) c_1 (O(1))^k inter [X]. $

(For $X$ a subvariety, $c_1 (O(1)) inter [X] = [X inter H]$, where $H$ is a hyperplane not containing $X$.)
]
#proof[
  For (b), denote by $M$ the homogeneous coordinate ring of $X$, which is a finitely generated graded module over the polynomial ring $S = kk[X_0, ..., X_n]$.
  By @Har77[I.7.4], there exists a filtration 
  $ 0 = M_0 subset M_1 subset ... subset M_r = M $
  such that each $M_i \/ M_(i-1)$ is isomorphic to a shifted copy of $S \/ frak(p)_i$ for some homogeneous prime ideal $frak(p)_i$.
  Hence, by the additivity of Hilbert polynomials and exact sequences $0 to M_k to M_{k+1} to M_{k+1}/M_k to 0$, we get
  $ d_k (X) = d_k (M) = sum d_k (S \/ frak(p)_i). $
  Denote by $frak(q)_j$ the homogeneous prime ideal of $S$ defining the irreducible variety $X_j$.
  By @Har77[I.7.4], we have ${frak(p)_i} = {frak(q)_j} cup {frak(q)'_j}$ counting multiplicity ($frak(q)_j$ has multiplicity $m_j$), where $frak(q)'_j$ is the non-minimal prime ideal in the set ${frak(p)_i}$.
  For a non-minimal prime ideal $frak(p)_i$, $Proj S \/ frak(p)_i$ has dimension strictly less than $k$.
  Hence $d_k (S \/ frak(p)_i) = 0$ for such $frak(p)_i$.
  Then we have
  $ d_k (X) = sum m_j d_k (S \/ frak(q)_j) + sum d_k (S \/ frak(q)'_j) = sum m_j d_k (X_j). $

  #indent
  For (c), we have the exact sequence
  $ 0 to cal(O)_X (t-m) to cal(O)_X (t) to cal(O)_(X inter H) (t) to 0. $
  By Serre vanishing, we have $H^1 (X, cal(O)_X (t-m)) = 0$ for $t >> 0$.
  Hence we get the exact sequence
  $ 0 to Gamma(X)_(t-m) to Gamma(X)_t to Gamma(X inter H)_t to 0 $
  for $t >> 0$.
  It gives 
  $ P_(X inter H) (t) = P_X (t) - P_X (t-m). $ 
  In particular, the first term of $P_(X inter H) (t)$ is 
  $ d_k (X) t^(k) / k! - d_k (X) (t-m)^(k) / k! = d_k (X) (k m t^(k-1)) / k! = m d_k (X) t^(k-1) / (k-1)! . $.
  Hence $d_(k-1) (X inter H) = m d_k (X)$.

  For (d), we can assume $X$ is irreducible by linearity of $d_k$ and $deg$.
  We do induction on $k$.
  If $k = 0$, then $X$ is a point and we have $P_X (t) = dim Gamma (X) = d_0 (X)$.
  Assume $k gt 0$.
  Let $H$ be a hyperplane not containing $X$.
  By (c), we have 
  $ d_k (X) = d_(k-1) (X inter H) = deg [X inter H] = deg [X]. $
]


#bibliography("../../../Accessories/ref.bib",style: "../../../Accessories/chicago-author-date_modified.csl")