#import "./note_for_myself.typ": *

#show: article_settings.with(
  section_level: "section",
  heading_number_mode: "level3-last",
  title: "title",
  author: "The author",
  date: datetime.today().display(),
  author_page: link("https://www.example.com")[My Homepage],
  version: "1.0.0",
)

#let CH = math.op("CH")
#let kk = math.bold("k")
#let rank = math.op("rank")
#let calO = math.cal("O")
#let calF = math.cal("F")
#let calT = math.cal("T")
#let Yang(content) = text(red)[Yang: #content]

== March 09: Basic of Foliations



=== Foliations in differential geometry

#definition[
  Let $M$ be a $n$-dimensional smooth manifold. 
  
+ A _foliated chart_ of dimension $r$ on $M$ is a pair $(U, phi)$, where $U$ is an open subset of $M$ and $phi: U arrow I^r times I^(n-r)$ is a diffeomorphism, where $I$ is the unit interval $(0, 1) subset RR$.

  A _plaque_ of $(U, phi)$ is a fiber of 
  $ U arrow I^r times I^(n-r) stretch(arrow.long)^(p_2) I^(n-r), $
  i.e. $phi^(-1)(I^r times {y})$ for some $y in I^(n-r)$.

+ A _foliated atlas_ of $M$ is a collection ${(U_alpha, phi_alpha)}_(alpha in Lambda)$ of foliated charts such that 
  + $union_(alpha in Lambda) U_alpha = M$,
  + for any $alpha, beta in Lambda$, $(U_alpha,phi_alpha)$ and $(U_beta, phi_beta)$ are _compatible_, i.e. for any plaque $P_alpha$, $P_beta$ of $(U_alpha, phi_alpha)$ and $(U_beta, phi_beta)$ respectively, $P_alpha inter P_beta$ is open in both $P_alpha$ and $P_beta$. 
    (Note that $P_alpha inter P_beta$ is also closed in $P_alpha inter (U_alpha inter U_beta)$ and $P_beta inter (U_alpha inter U_beta)$, hence $P_alpha inter P_beta$ is a union of connected components of both $P_alpha$ and $P_beta$.) 
    In other words, 
    $ {"connected components of" P_alpha inter U_alpha inter U_beta} = {"connected components of " P_beta inter U_alpha inter U_beta}. $

+ Two foliated atlases are _equivalent_ if their union is a foliated atlas. 
  A _foliation_ on $M$ is an equivalence class of foliated atlases on $M$.

+ A _leaf_ of a foliation on $M$ is a *connected* subset $L subset M$ which is union of at most countably many plaques such that for any plaque $P$ of any foliated chart, we have $L inter P = emptyset$ or $P subset L$.
]

#remark[
  $M = union.sq "leaves"$.
  Every leaf is a manifold with an "injection" to $M$.
]

#example[
  Let $M$, $N$ be smooth manifolds.
  A map $pi : M arrow N$ is a _submersion_ if for any $x in M$, the differential $d_x pi : T_x M arrow T_{pi(x)} N$ is surjective.
  By implicit function theorem, locally $pi$ is diffeomorphic to the projection $I^m arrow I^(m-r)$.
  Then the collection of charts of $M$ which are compatible with $pi$ forms a foliated atlas, and hence defines a foliation on $M$.
  In this case, the leaves are the connected components of fibers of $pi$.
]

Let $M$ be a smooth manifold, and $calT_M$ be the sheaf of smooth vector fields on $M$.
Recall the _Lie bracket_ of $calT_M$ is a map
$ [ - , - ] : calT_M times calT_M arrow calT_M, #h(2em) [D_1, D_2] = D_1 D_2 - D_2 D_1. $

Let $calF subset calT_M$ be a locally free subsheaf of $calT_M$ of rank $r$ such that $calF|_x arrow calT_M|_x$ is injective for any $x in M$.

#definition[
  We say $calF$ is _involutive_ if it is closed under the Lie bracket, i.e. for any open subset $U subset M$ and any $D_1, D_2 in calF(U)$, we have $[D_1, D_2] in calF(U)$.
]

#theorem("Frobenius")[
  Let $M$ be a manifold.
  There is a canonical bijection between foliations on $M$ and involutive locally free subsheaves of $calT_M$.
  $ {"foliations on " M} <--> {"involutive subbundle of" calT_M} $
]<thm:Frobenius>
#proof("Idea of proof")[
  #Yang([])
+ foliation $arrow$ involutive subbundle: 

  For chart $(U , phi)$ of $M$, we have $pi : U arrow I^r times I^(n-r)$.
  On $I^r times I^(n-r)$, we have the standard coordinate $x_1, ..., x_n$.
  Then $calF(U)$ is generated by $D_i = pi^* (partial / partial x_i)$ for $i = 1, ..., r$.
  Glueing $calF(U)$ for all charts $U$ gives an involutive subbundle of $calT_M$.

+ involutive subbundle $arrow$ foliation:
  
  Let $calF$ be an involutive subbundle of $calT_M$.
  If $ rank calF = 1$, $calF$ is locally generated by a single vector field $D$.
  From any point $x in M$, we can construct a integral curve $L$ of $D$ passing through $x$ by solving the ODE defined by $D$.

  If $rank calF = r > 1$, take $r$ local generators $D_1, ..., D_r$ of $calF$.
  Solve some liner PDE defined by $D_1, ..., D_r$ to get a local chart of $M$ which is compatible with $calF$.
]

#remark[
+ Let $calF subset calT_M$ be an involutive subbundle of $calT_M$ with a leaf $L subset M$.
  Then the tangent bundle of $L$ is just $calF|_L$, i.e. 
  $ calF|_L = Im(calT_L arrow calT_M|_L). $

+ Under $phi: U arrow I^r times I^(m-r) arrow I^(m-r)$ with coordinates $x_1, ..., x_n$ and $calF(U)$ generated by $D_i = pi^* (partial / partial x_i)$ for $i=1...r$, the coordinates $x_{r+1}, ..., x_m$ are annihilated by $calF(U)$.

  Abstractly, to get $U arrow I^{m-r}$, need $C^infinity$ functions $f_1,...,f_(m-r)$ on $U$ with $p_2 = (f_1,...f_(m-r))$ and $D f_j = 0$ for all $D in calF$.
]

#example[
  Let $M = RR^2$ with coordinate $x,y$, and $D = a partial_x + b partial_y$ with $a,b$ nonzero constant.
  Then $D f = 0$ implies $f = b x - a y$.
  Then $f: RR^2 arrow RR$ defines a foliation with leaves given by the level sets of $f$, i.e. ${b x - a y = c}$ for some constant $c$.
]

#example[
  Let $M = RR^2 \\ {0}$ with coordinate $x,y$, and $D = a y partial_x + b x partial_y$ with $a$ nonzero constant.
  Let $calF$ be the involutive subbundle of $calT_M$ generated by $D$.
  
  How to solve $D f = 0$?
  
  Assume $L$ is a leaf.
  Then $calT_L$ is generated by $D|_L$.
  Consider a differential $1$-form $omega$ on $M$ such that $chevron.l omega,D chevron.r = 0$, here $chevron.l -,- chevron.r$ is the natural pairing between $calT_M$ and $Omega^1_M$.
  Write $omega = u d x + v d y$, then $chevron.l omega, D chevron.r = a y u + b x v$.
  We can take $omega = -b x d x + a y d y$.
  Note that $omega|_L = 0$.
  View $x,y$ as $C^infinity$-functions on $L$ by pull-back.
  View $omega|_L = 0$ as ODE on $L$.
  Then we get $d (b x^2 - a y^2) = 0$.
  Hence $f = b x^2 - a y^2$ is a solution of $D f = 0$.

  Then $f: RR^2 \\ {0} arrow RR$ defines a foliation with leaves given by the level sets of $f$.

  Consider two case and their pictures: #Yang([]).
]

#example[
  Let $M = (RR \/ ZZ)^2$.
  On its universal cover $RR^2$, we fix a coordinate $x,y$.
  Let $tilde(D) = a partial_x + b partial_y$.
  It is translation invariant and hence descedns to a vector field $D$ on $M$.

  We get two foliation $tilde(calF)$ on $tilde(M)$ generated by $tilde(D)$ and $calF$ on $M$ generated by $D$.
  Then leaves of $calF$ on $M$ are image of leaves of $tilde(calF)$ under $pi: tilde(M) arrow M$.
  Let $L_0$, $tilde(L_0)$ be leaves through $0$.

  For example, $a = 3, b = 1$.
  #Yang[]
  Then $L_0$ is a closed loop.

  Hence in case $a / b in QQ$, we get a closed loop in $M$.
  Otherwise, we get a dense curve in $M$.
  And hence it is not close in $M$.
]

=== Complex settings

Let $M$ be a complex manifold of complex dimension $m$.
We can define _holomorphic foliations_ on $M$ by replacing "smooth" with "holomorphic" and "unit interval" with "unit disk".
The Frobenius theorem (@thm:Frobenius) also holds in this setting.

#example[
  Let $M = E_1 times E_2$ where $E_1$, $E_2$ are elliptic curves.
  Write $E_i = CC \/ Lambda_i$ for $i = 1, 2$.
  Let $D_i in Gamma(E_i, calT_(E_i))$ be a nonzero vector field for $i = 1, 2$.
  Take $D = a p_1^* D_1 + b p_2^* D_2$ for some nonzero constant $a, b$ under $calT_M tilde.equiv p_1^* calT_(E_1) plus.o p_2^* calT_(E_2)$.

  Then $D$ defines a holomorphic foliation on $M$.
  Let $L_0$ be the leaf through $0$.
  Then $L_0 subset M$ is "locally" a holomorphic submanifold of $M$.
  The Chow theorem says that $L_0$ is algebraic if and only if $L_0$ is closed in $M$.

  Case 1: $E_1$ is not isogenous to $E_2$.
  Then $L_0$ is never algebraic.
  Otherwise, the algebraicity of $L_0$ implies that it is an elliptic curve, and hence $E_1$ is isogenous to $E_2$ by $L_0$.

  Case 2: $E_1 = E_2 = E$ and $D_1 = D_2 = D_0$.
  If $a / b in RR \\ QQ$, then $L_0$ is dense in $M$ and hence not algebraic.
]